# Generated by Django 2.2.3 on 2019-07-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_type', models.IntegerField(choices=[(1, '身份证'), (2, '驾照'), (3, '银行卡'), (4, '其他')])),
                ('pic_name', models.CharField(max_length=30)),
                ('pic_path', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
