# Generated by Django 2.2.3 on 2019-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190723_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picinfo',
            name='pic_path',
            field=models.CharField(max_length=50),
        ),
    ]
