# Generated by Django 2.2.3 on 2019-07-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190708_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
