# Generated by Django 2.2.3 on 2019-07-09 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190709_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='id',
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.UserInfo'),
        ),
    ]
