# Generated by Django 2.2.3 on 2019-07-09 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190709_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user',
            new_name='user_id',
        ),
    ]
