# Generated by Django 2.2.3 on 2019-07-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190709_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_detil',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoken',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo'),
            preserve_default=False,
        ),
    ]
