# Generated by Django 2.2.3 on 2019-07-09 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190709_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.IntegerField(choices=[(1, '提交成功'), (2, '提交失败'), (3, '任务完成但有问题'), (4, '任务完成')])),
                ('task_ctime', models.DateTimeField(auto_now_add=True)),
                ('result_pic', models.CharField(max_length=3200000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_status', models.IntegerField(choices=[(1, '上传成功'), (2, '上传失败'), (3, '抠图成功'), (4, '抠图失败'), (5, '图片重复')])),
                ('pic_name', models.CharField(max_length=64)),
                ('pic_uuid', models.CharField(max_length=64)),
                ('pic_ctime', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
    ]
