# Generated by Django 2.2.3 on 2019-07-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_picinfo_taskinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='org_pic',
            field=models.CharField(default=1, max_length=3200000),
            preserve_default=False,
        ),
    ]
