# Generated by Django 2.2.3 on 2019-07-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_taskinfo_org_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picinfo',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='taskinfo',
            old_name='user',
            new_name='user_id',
        ),
    ]
