# Generated by Django 2.2.3 on 2019-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190709_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='org_pic_name',
            field=models.CharField(default=1, max_length=6400000),
            preserve_default=False,
        ),
    ]
