# Generated by Django 2.2.3 on 2019-07-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_taskinfo_org_pic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskinfo',
            name='error_pic_name',
            field=models.CharField(default=1, max_length=3200000),
            preserve_default=False,
        ),
    ]
