# Generated by Django 2.2.3 on 2019-07-11 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_taskinfo_error_pic_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picinfo',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='taskinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
