# Generated by Django 3.0 on 2020-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('bbox', models.CharField(max_length=200)),
                ('mark', models.CharField(max_length=10)),
                ('fix', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('choice', models.CharField(max_length=10)),
            ],
        ),
    ]
