# Generated by Django 2.2.3 on 2019-08-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(max_length=11)),
                ('status', models.IntegerField(max_length=10)),
                ('user', models.CharField(default='NULL', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Mark_Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('class_id', models.IntegerField(max_length=11)),
                ('t', models.FloatField(max_length=40)),
                ('r', models.FloatField(max_length=40)),
                ('b', models.FloatField(max_length=40)),
                ('l', models.FloatField(max_length=40)),
                ('value', models.FloatField(max_length=50)),
                ('isMain', models.IntegerField(max_length=11)),
                ('status', models.IntegerField(choices=[(0, '未处理'), (1, '相似'), (2, '不相似'), (3, '无法判断')])),
            ],
        ),
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, 'vip'), (3, 'svip'), (4, 'amdin')])),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_detil', models.CharField(max_length=60)),
            ],
        ),
    ]
