# Generated by Django 2.2.3 on 2019-09-03 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, 'vip'), (3, 'svip'), (4, 'amdin')])),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('user_detil', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TaskInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_status', models.IntegerField(choices=[(1, '提交成功'), (2, '提交失败'), (3, '任务完成但有问题'), (4, '任务完成')])),
                ('task_ctime', models.DateTimeField(auto_now_add=True)),
                ('org_pic_name', models.CharField(max_length=6400000)),
                ('error_pic_name', models.CharField(max_length=3200000)),
                ('org_pic', models.CharField(max_length=3200000)),
                ('result_pic', models.CharField(max_length=3200000)),
                ('bg', models.CharField(max_length=3200000)),
                ('size', models.CharField(max_length=3200000)),
                ('org_size', models.CharField(max_length=3200000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_status', models.IntegerField(choices=[(1, '上传成功'), (2, '上传失败'), (3, '抠图成功'), (4, '抠图失败'), (5, '图片重复')])),
                ('pic_name', models.CharField(max_length=64)),
                ('pic_uuid', models.CharField(max_length=64)),
                ('pic_ctime', models.DateTimeField(auto_now_add=True)),
                ('pic_size', models.CharField(max_length=64)),
                ('pic_org_size', models.CharField(max_length=64)),
                ('pic_bg', models.CharField(max_length=64)),
                ('org_pic_url', models.CharField(max_length=200)),
                ('result_pic_url', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TaskInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserInfo')),
            ],
        ),
    ]
