# Generated by Django 3.0 on 2019-12-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tripletmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid1', models.CharField(max_length=100)),
                ('uuid2', models.CharField(max_length=100)),
                ('bbox1', models.CharField(max_length=100)),
                ('bbox2', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=10)),
                ('fix', models.CharField(max_length=10)),
            ],
        ),
    ]
