# Generated by Django 3.0 on 2020-01-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tripletmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid1', models.CharField(max_length=500)),
                ('uuid2', models.CharField(max_length=500)),
                ('bbox1', models.CharField(max_length=100)),
                ('bbox2', models.CharField(max_length=100)),
                ('mark', models.CharField(max_length=10)),
                ('fix', models.CharField(max_length=10)),
                ('status', models.CharField(db_index=True, default='0', max_length=10)),
                ('types', models.CharField(max_length=30)),
            ],
        ),
    ]
